version: '3'

services:
  db:
    image: postgres:latest

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8899
    volumes:
      - .:/code
    ports:
      - "8899:8899"
    depends_on:
      - db
